services:
  weaviate:
    image: semitechnologies/weaviate:1.28.0
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      ENABLE_MODULES: text2vec-huggingface
      HUGGINGFACE_APIKEY: "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"  # Вставьте сюда ваш токен
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
